global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['snaapio-prometheus.onrender.com']
      
  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['snaapio-loki.onrender.com']

  - job_name: 'nestjs'
    scrape_interval: 2s
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['snaapio-backend-latest.onrender.com']
