global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snaapio_server'
    scrape_interval: 2s
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['snaapio-backend-latest.onrender.com']